Models/Setting/Lesson.cs
using Dotnet.Models.Generic;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAD.Models.Setting {

    [ToString]
    [Table("Lesson")]
    public class Lesson : GenericEntity {

        [Required]
        [MaxLength(20)]
        [Display(Name = "名稱")]
        public string Name;

        [MaxLength(30)]
        [Display(Name = "說明")]
        public string Description;

        public List<TeachingAid> TeachingAids;
    }
}

Models/Setting/TeachingAid.cs
using Dotnet.Models.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAD.Models.Setting {

    [ToString]
    [Table("Teaching_Aid")]
    public class TeachingAid : GenericEntity {

        [MaxLength(5)]
        [Display(Name = "序號")]
        public string Seq;


        [MaxLength(20)]
        [Display(Name = "說明")]
        public string Description;

        [Required]
        [MaxLength(30)]
        [Display(Name = "檔名")]
        public string FileName;

        public Lesson Lesson;
    }
}

Controllers/Setting/SettingController.cs
using Anotar.Log4Net;
using CAD.Models.Setting;
using Dotnet.Services.Generic;
using Dotnet.Utils.Common;
using LinqKit;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Linq;
using System.Text;

namespace CAD.Controllers.Setting {

    [Route("[controller]")]
    public class SettingController : Controller {

        private readonly IGenericService<Lesson> lessonService;

        public SettingController(IGenericService<Lesson> lessonService) {

            this.lessonService = lessonService;
        }

        [HttpGet("LessonList")]
        public IActionResult LessonList() {

            return View();
        }

        [HttpGet("LessonGrid")]
        public JsonResult LessonGrid([FromQuery]Lesson form) {

            LogTo.Debug("Name:" + form.Name + ", Description:" + form.Description);

            var predicate = PredicateBuilder.New<Lesson>(true);
            if (!StringUtils.TrimIsNull(form.Name)) {
                predicate = predicate.And(lesson => lesson.Name.Contains(form.Name));
            }

            if (!StringUtils.TrimIsNull(form.Description)) {
                predicate = predicate.And(user => user.Description.Contains(form.Description));
            }

            var users = lessonService.GetAll(predicate);
            return Json(users);
        }

        /// <summary>
        /// Uploads an image to the server.
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        /// 
        [HttpPost("UploadImage/{type}")]
        public IActionResult UploadImage(string type) {

            try {
                string fileName = CommonUtils.UploadFile(Request.Form.Files, "images\\" + type);
                return Json(fileName);
            } catch (Exception ex) {
                return Json("Upload Failed: " + ex.Message);
            }
        }

        [HttpGet("LessonAdd")]
        public IActionResult LessonAdd() {

            return View(new Lesson());
        }

        [HttpPost("LessonAdd")]
        [ValidateAntiForgeryToken]
        public IActionResult LessonAdd([FromForm]Lesson form) {

            LogTo.Debug("form:" + form);
            if (ModelState.IsValid) {
                lessonService.Insert(form);
            }
            return Json(CommonUtils.GetJsonResult(ModelState, Url.Action("LessonList")));
        }


        [HttpGet("LessonEdit/{id}")]
        public IActionResult LessonEdit(string id) {

            var dbLesson = lessonService.GetById(id);
            return View(dbLesson);
        }


        [HttpPost("LessonEdit")]
        [ValidateAntiForgeryToken]
        public IActionResult LessonEdit([FromForm]Lesson form) {

            form.TeachingAids.ToList().ForEach(teachingAid => LogTo.Debug("TechingAid:" + teachingAid.Description));
            
            if (ModelState.IsValid) {
                lessonService.Update(form);
            }
            return Json(CommonUtils.GetJsonResult(ModelState, Url.Action("LessonList")));
        }


        [HttpGet("LessonProject/{id}")]
        public IActionResult LessonProject(string id) {
            var lesson = lessonService.GetById(id);
            return View(lesson);
        }
        
    }
}

Utils/Enum/EnumsToJavaScriptViewComponent.cs
using Dotnet.Models.Web;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace Dotnet.Utils.Enum {

    /// <summary>
    /// 參考: https://dzone.com/articles/aspnet-core-building-an-enum-provider-to-convert-c
    /// </summary>
    public class EnumsToJavaScriptViewComponent : ViewComponent {
        private readonly IEnumProvider _enumProvider;

        public EnumsToJavaScriptViewComponent(IEnumProvider enumProvider) {
            _enumProvider = enumProvider;
        }

        public Task<HtmlString> InvokeAsync() {
            var buffer = new StringBuilder(10000);

            foreach (var jsEnum in _enumProvider.GetEnumTypes()) {
                buffer.Append("var ");
                buffer.Append(jsEnum.Name);
                buffer.Append(" = ");
                buffer.Append(EnumToString(jsEnum));
                buffer.Append("; \r\n");
            }
            //buffer.Append("\r\n Vue.component('v-select', VueSelect.VueSelect);");
            return Task.FromResult(new HtmlString(buffer.ToString()));
        }

        private static string EnumToString(Type enumType) {
            var values = System.Enum.GetValues(enumType);
            List<DdlItem> ddls = new List<DdlItem>();   
            foreach (var value in values) {
                DdlItem ddl = new DdlItem(value.ToString(), value.GetType().GetMember(value.ToString()).FirstOrDefault()?.GetCustomAttribute<DescriptionAttribute>()?.Description);

                ddls.Add(ddl);
            }

            return JsonConvert.SerializeObject(ddls);
        }
    }
}

Views/Setting/LessonAdd.cshtml
@{
    ViewBag.Title = "新增課程";
}

<div class="container">
    <br /><h4>新增課程</h4>
    <!-- 畫面驗證訊息 -->
    <div class='validation-summary-errors'><ul /></div>

    <div class="form-group row">
        <label class="col-lg-2 text-right"><span style="color: red">＊</span>名稱</label>
        <div class="col-lg-4">
            <input class="form-control" v-model="model.Name" />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-lg-2 text-right">說明</label>
        <div class="col-lg-4">
            <textarea class="form-control" v-model="model.Description" rows="3" cols="10"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">
            <button type="button" class="btn btn-warning" v-on:click="addRow">新增明細</button>
            <table class="table-bordered w-100">
                <thead>
                    <tr class="d-flex">
                        <th class="col-1">操作</th>
                        <th class="col-1">序號</th>
                        <th class="col-4">說明</th>
                        <th class="col-6"><span style="color: red">＊</span>圖片</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(row, index) in rows" class="d-flex">
                        <td class="text-center col-1">
                            <button type="button" class="btn btn-danger btn-sm" v-on:click="removeRow(row)"><i class='fa fa-remove'></i>刪除</button>
                        </td>
                        <td class="text-center col-1" style="vertical-align:middle">
                            {{index + 1}}
                            <input type="hidden" v-model="row.Seq" />
                        </td>
                        <td class="text-center col-4">
                            <input v-model="row.Description" class="form-control">
                        </td>
                        <td class="col-6">
                            <input type="file" class="filestyle" v-on:change="fileChange($event, index)" v-bind:data-placeholder="row.FileName" />
                            <img v-bind:src="'/images/Lesson/' + row.FileName" v-if="!previewImage[index] && !!row.FileName" class="w-25" />
                            <span v-else>
                                <img v-bind:src="previewImage[index]" class="w-25" />
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="text-center">
        <input type="button" class="btn btn-primary" value="儲存" v-on:click="save" />
        <input type="button" class="btn btn-warning" value="上一頁" v-on:click="previousPage" />
    </div>
</div>

<script src="~/js/bundle.js"></script>


<script type="text/javascript">
    
var vm =
    new Vue({
        el: '.container',
        data: {
            errors: [],
            model: {},
            rows: [],
            formdata: new FormData(),
            previewImage: []
        },
        watch: {
            rows: function () {
                // 處理filestyle, 新增列後再驅動timer
                setTimeout(function () {
                    $('.filestyle').each(function () {
                        if (!$(this).attr("id")) {
                            $(this).filestyle();
                        }
                    });
                }, 0);
            }
        },
        methods: {
            fileChange: async function (e, index) {
                var files = e.target.files || e.dataTransfer.files;
                if (!files.length) {
                    return;
                }

                this.formdata.append(files[0].name, files[0]);
                await uploadFile(files[0]).then(function (file) {

                    if (vm.previewImage[index] === "undefined") {
                        vm.previewImage.push(file);
                    } else {
                        vm.previewImage[index] = file;
                    }
                    vm.rows[index].FileName = files[0].name;
                });
            },
            save() {
                this.model.TeachingAids = this.rows;
                alert(JSON.stringify(this.model));

                ajaxUpload('/Setting/LessonAdd', this.model, '/Setting/UploadImage/Lesson', this.formdata);
            },
            addRow() {
                this.rows.push({ Seq: this.rows.length + 1, Description: "", FileName: "" });
                this.previewImage.push('');
                //console.log("previewImage length:" + this.previewImage.length);
            },
            removeRow(selectedRow) {
                if (this.rows.length == 1) {
                    warningMessage("明細資料至少要有一列");
                } else {
                    var index = this.rows.indexOf(selectedRow);
                    //console.log(index);
                    this.$delete(this.rows, index);
                    //this.rows.splice(index, 1);

                    // 重置序號
                    this.rows.forEach(function (row, idx) {
                        row.Seq = idx + 1;
                    });


                    this.previewImage.splice(index, 1);
                    //console.log("previewImage length:" + this.previewImage.length);

                    $(".filestyle").each(function (idx) {
                        if (idx >= index) {
                            $(this).filestyle('clear');
                            if (!!vm.rows[idx] && !!vm.rows[idx].FileName) {
                                //console.log("idx:" + idx + ", value:" + vm.rows[idx].FileName);
                                $(this).filestyle('placeholder', vm.rows[idx].FileName);
                            }
                        }
                    });
                }
            }
        },
        created() {
            this.addRow();
        }
    })

</script>

Views/Setting/LessonEdit.cshtml
@{
    ViewBag.Title = "編輯課程";
}

<div class="container">
    <br /><h4>編輯課程</h4>
    <!-- 畫面驗證訊息 -->
    <div class='validation-summary-errors'><ul /></div>

    <div class="form-group row">
        <label class="col-lg-2 text-right"><span style="color: red">＊</span>名稱</label>
        <div class="col-lg-4">
            <input class="form-control" v-model="model.Name" />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-lg-2 text-right">說明</label>
        <div class="col-lg-4">
            <textarea class="form-control" v-model="model.Description" rows="3" cols="10"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">
            <button type="button" class="btn btn-warning" v-on:click="addRow">新增明細</button>
            <table class="table-bordered w-100">
                <thead>
                    <tr class="d-flex">
                        <th class="col-1">操作</th>
                        <th class="col-1">序號</th>
                        <th class="col-4">說明</th>
                        <th class="col-6"><span style="color: red">＊</span>圖片</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(row, index) in rows" class="d-flex">
                        <td class="text-center col-1">
                            <button type="button" class="btn btn-danger btn-sm" v-on:click="removeRow(row)"><i class='fa fa-remove'></i>刪除</button>
                        </td>
                        <td class="text-center col-1" style="vertical-align:middle">
                            {{index + 1}}
                            <input type="hidden" v-model="row.Seq" />
                        </td>
                        <td class="text-center col-4">
                            <input v-model="row.Description" class="form-control">
                        </td>
                        <td class="col-6">
                            <input type="file" class="filestyle" v-on:change="fileChange($event, index)" v-bind:data-placeholder="row.FileName" />
                            <img v-bind:src="'/images/Lesson/' + row.FileName" v-if="!previewImage[index] && !!row.FileName" class="w-25" />
                            <span v-else>
                                <img v-bind:src="previewImage[index]" class="w-25" />
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="text-center">
        <input type="button" class="btn btn-primary" value="儲存" v-on:click="save" />
        <input type="button" class="btn btn-warning" value="上一頁" v-on:click="previousPage" />
    </div>
</div>

<script src="~/js/bundle.js"></script>


<script type="text/javascript">

var vm =
    new Vue({
        el: '.container',
        data: {
            errors: [],
            model: @Html.Raw(Json.Serialize(Model)),
            rows: @Html.Raw(Json.Serialize(Model.TeachingAids)),
            formdata: new FormData(),
            previewImage: []
        },
        watch: {
            rows: function () {
                // 處理filestyle, 新增列後再驅動timer
                setTimeout(function () {
                    $('.filestyle').each(function () {
                        if (!$(this).attr("id")) {
                            $(this).filestyle();
                        }
                    });
                }, 0);
            }
        },
        methods: {
            fileChange: async function (e, index) {
                var files = e.target.files || e.dataTransfer.files;
                if (!files.length) {
                    return;
                }

                this.formdata.append(files[0].name, files[0]);
                await uploadFile(files[0]).then(function (file) {

                    if (vm.previewImage[index] === "undefined") {
                        vm.previewImage.push(file);
                    } else {
                        vm.previewImage[index] = file;
                    }
                    vm.rows[index].FileName = files[0].name;
                });
            },
            save() {
                // alert(JSON.stringify(this.model));
                // alert(JSON.stringify(this.rows));
                this.model.TeachingAids = this.rows;
                ajaxUpload('/Setting/LessonEdit', this.model, '/Setting/UploadImage/Lesson', this.formdata);
            },
            addRow() {
                this.rows.push({ Seq: this.rows.length + 1, Description: "", FileName: "" });
                this.previewImage.push('');
                // console.log("previewImage length:" + this.previewImage.length);
            },
            removeRow(selectedRow) {
                if (this.rows.length == 1) {
                    warningMessage("明細資料至少要有一列");
                } else {
                    var index = this.rows.indexOf(selectedRow);
                    //console.log(index);
                    this.$delete(this.rows, index);

                    this.previewImage.splice(index, 1);
                    //console.log("previewImage length:" + this.previewImage.length);

                    // 重置序號
                    this.rows.forEach(function (row, idx) {
                        row.Seq = idx + 1;
                    });
                    // 處理placeholder
                    $(".filestyle").each(function (idx) {
                        if (idx >= index) {
                            $(this).filestyle('clear');
                            if (!!vm.rows[idx] && !!vm.rows[idx].FileName) {
                                //console.log("idx:" + idx + ", value:" + vm.rows[idx].FileName);
                                $(this).filestyle('placeholder', vm.rows[idx].FileName);
                            }
                        }
                    });
                }
            }
        }
    })

</script>

Views/Setting/LessonList.cshtml
@{
    ViewBag.Title = "課程管理";
}

<div class="container">
    <br /><h4>課程管理</h4><br />

    <section class="well">
        <div class="form-group row">
            <label class="col-lg-2">顯示</label>
            <div class="col-lg-2">
                <v-select v-model="model.Status" :options="yesNo" :blank="true" />
            </div>

            <div class="col-lg-offset-6">
                <button type="button" class="btn btn-primary" v-on:click="getData();">查詢</button>
            </div>
        </div>
    </section>
    <div>
        <input type="button" class="btn btn-warning" value="新增課程" onclick="location.href='/Setting/LessonAdd'" />
    </div>
    <datatable :columns="columns" :data="rows"></datatable>
    <datatable-pager v-model="page" type="abbreviated" class="d-flex justify-content-center"></datatable-pager>
</div>
<script src="~/js/bundle.js"></script>


<script type="text/javascript">
    
    @await Component.InvokeAsync("EnumsToJavaScript")

var vm =
    new Vue({
        el: '.container',
        data: {
            columns: [
                {
                    label: "操作", interpolate: true, align: "center", sortable: false,
                    representedAs: function (row) {
                        return editDeleteButton("/Setting/LessonEdit/", "/Setting/LessonDelete/", row.Id) + projectButton("/Setting/LessonProject/", row.Id);
                    }
                },
                { label: "名稱", field: "Name" },
                { label: "說明", field: "Description" }
            ],
            rows: [],
            model: {},
            page: 1,
            yesNo: YesNo
        },
        mounted: function () {
            window.addEventListener('keypress', function (event) {
                if (event.key == "Enter") {
                    vm.getData();
                }
            });
        },
        methods: {
            getData() {
                blockUI();

                axios.get('/Setting/LessonGrid', {
                    params: this.model
                })
                .then(response => {
                    //alert(JSON.stringify(response.data));
                    this.rows = response.data;
                    $.unblockUI();
                });
            }
        },
        created() {
            this.getData();
        }
    });
</script>

Views/Setting/LessonProject.cshtml
@{
    Layout = null;
}


<head>
    <link rel="stylesheet" href="~/css/bundle.css" />
    <style>
        img {
            width: 65%;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<div class="container">
    <!--
    <textarea id="source">
    class: center, middle

    # 社交故事

    ---

    image11.png

    ---

    image17.png
    </textarea>
    -->
</div>
<script src="~/js/bundle.js"></script>


<script type="text/javascript">

var vm =
    new Vue({
        el: '.container',
        data: {
            model: @Html.Raw(Json.Serialize(Model))
        },
        mounted: function () {

            //var slideshow = remark.create();
            //alert(JSON.stringify(this.model));
            
            var slideshow = remark.create({
                source: this.composeContent(this.model)
            });
            
        },
        methods: {
            composeContent(model) {
                var content = "class: center, middle\n" +
                              "# " + model.Name + "\n";

                model.TeachingAids.forEach(function (row) {
                    //alert(JSON.stringify(row));
                    content += "\n---\n";
                    content += "class: center, middle\n";
                    content += "<img src='/images/Lesson/" + row.FileName + "' onclick='speak(\"" + row.Description + "\")'>";
                });

                console.log(content);
                return content;
            }
            
        }
    });


    function speak(message) {
        if (!!message) { 
            //console.log(message);
            var rate = 5;
            var pitch = 2;
        
            var msg = new SpeechSynthesisUtterance();
            var voices = window.speechSynthesis.getVoices();
            msg.voice = voices[0];
            msg.rate = rate / 10;
            msg.pitch = pitch;
            msg.text = message;

            speechSynthesis.speak(msg);
        }
    }
</script>